/**
 * This file is generated by openapi-typescript.
 * Run: scripts/gen-api-client.sh ../meta-ads-backend/openapi.json
 */

export interface components {
  schemas: {
    TimeseriesResponse: {
      data: Array<{
        date: string
        spend: number
        roas: number
      }>
      timezone_name: string
      account_currency: string
    }
  }
}
